### ISSUE TITLE
Последняя версия 1.3.0 выдаёт ошибку

### ISSUE THREAD

**Issue by kamuz** [bezumkin/modx-markdown#8]
Пакет собирал сам. Он не находит этот файл в сниппете `Markdown`

```php
require_once MODX_CORE_PATH . 'components/markdown/vendor/autoload.php';
```

Который был отлючен в *.gitignore*

```
/core/components/markdown/vendor/
```

**Comment by kamuz** [comment]
Предыдущая версия 1.2.0 работает нормально.

**Comment by bezumkin** [comment]
При самостоятельной сборке нужно [использовать composer](https://github.com/bezumkin/modx-markdown/blob/master/core/components/markdown/composer.json)

**Comment by kamuz** [comment]
Спасибо. Теперь всё гуд
